server:
  port: 8089

spring:
  application:
    name: reward-service

  kafka:
    bootstrap-servers: kafka:9092   # ðŸ”´ IMPORTANT
    consumer:
      group-id: reward-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.paypal.reward_service.entity.Transaction
        spring.json.use.type.headers: false
